# Generated by Django 3.2.13 on 2022-11-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='movie',
        ),
    ]
