# Generated by Django 3.2.13 on 2022-11-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mvti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.mvti'),
        ),
    ]
